
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 27 16:17:20 CEST 2020
//----------------------------------------------------

package yal.analyse;

/** CUP generated class containing symbol constants. */
public class CodesLexicaux {
  /* terminals */
  public static final int FONCTION = 30;
  public static final int PARENTHESEDROITE = 25;
  public static final int TANTQUE = 14;
  public static final int EGAL = 26;
  public static final int REPETER = 15;
  public static final int SI = 10;
  public static final int VIRGULE = 32;
  public static final int FIN = 4;
  public static final int LIRE = 7;
  public static final int LONGUEUR = 36;
  public static final int PARENTHESEGAUCHE = 24;
  public static final int CROCHETDROITE = 34;
  public static final int OU = 29;
  public static final int NON = 21;
  public static final int AFFECT = 9;
  public static final int DIFFERENT = 27;
  public static final int DEBUT = 3;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int RETOURNE = 31;
  public static final int ET = 28;
  public static final int CROCHETGAUCHE = 33;
  public static final int IDF = 37;
  public static final int SINON = 12;
  public static final int ALORS = 11;
  public static final int SOUSTRACTION = 18;
  public static final int POINT = 35;
  public static final int CSTENTIERE = 38;
  public static final int SUPERIEUR = 23;
  public static final int ADDITION = 17;
  public static final int PROGRAMME = 2;
  public static final int FINTANTQUE = 16;
  public static final int POINTVIRGULE = 5;
  public static final int ENTIER = 8;
  public static final int INFERIEUR = 22;
  public static final int FINSI = 13;
  public static final int DIVISION = 20;
  public static final int MULTIPLICATION = 19;
  public static final int ECRIRE = 6;
}

